# ===========================================
# Site Information Settings
# ===========================================


# Site creation time
since: 2018

# Custom your favicon.ico in `site/source`
favicon: /favicon.ico


# Set feed link (false | default | your feed link)
# false: disable
# default: use `atom.xml`, generator for `hexo-generator-feed`
rss: default

# ===========================================
# Menu Settings
# ===========================================
menu:
  Archives: /archives
  About: /about/me.html
  Project: /project
  Todo: /todo

# ===========================================
# Widget Settings
# ===========================================
# widget function
# false: disable
# widget_custom: custom your widget
#   title: your widget title
#   content: Add your html code in here. Example: <p>testing...</p>
widget:
  Tags: true
  Categories: false 
  Custom: false 

widget_custom:
    title: Player 
    content: <iframe frameborder="no" border="0" marginwidth="0" marginheight="0" width=330 height=450 src="//music.163.com/outchain/player?type=4&id=792201363&auto=0&height=430"></iframe>

# widget_custom2:
#     title: Player2 
#     content: <p><a href="www.baidu.com">test</a></p>



# ===========================================
# Theme Settings
# ===========================================
# theme styling
# color: Default | Mint Green | Cobalt Blue | Hot Pink | Dark Violet
theme:
  color: Default
  fancybox: true

mathjax:
  enable: true
# ===========================================
# Third Party Services Settings
# ===========================================

# Baidu Analytics
baidu_analytics: 
# Google Analytics
google_analytics: 

# Duoshuo
duoshuo_shortname: 
# Disqus
disqus_shortname: zivyou

latex: true


languages: zh-cn
# ===========================================
# Version
# ===========================================
version: 1.1
